// react-spa/src/components/list/BookList.tsx
import { getDemoBooks } from "../../demo-data.ts";
import { Book } from "../../types.ts";
import BookCard from "./BookCard.tsx";

export default function BookList() {
  // getDemoBooks liefert eine Liste mit Büchern
  //  - im nächsten Schritt lesen wir die Liste vom Server
  const books: Book[] = getDemoBooks();

  // todo: Render eine Liste von BookCard-Komponenten
  //   - die Bücher, die ausgegeben werden müssen, stehen im books-Array
  //   - verwende die JavaScript map-Funktion
  //   - jedes book soll mit der BookCard dargestellt werden
  //       (Die BookCard-Komponente musst du implementieren, s. dort)
  //   - denk' dran, dass du bei der Verwendung der BookCard in der
  //     Liste das 'key'-Attribut angeben musst!

  return (
    <div className="p-2">
      {books.map((b) => (
        <BookCard key={b.id} book={b} />
      ))}
    </div>
  );
}

// angular-spa/src/app/book-list/book-list.ts
import { Component } from '@angular/core';
import { Book } from '../book.model';
import { getDemoBooks } from '../demo-data';

@Component({
  selector: 'app-book-list',
  templateUrl: './book-list.html',
})
export class BookList {
  // getDemoBooks liefert eine Liste mit Büchern
  //  - im nächsten Schritt lesen wir die Liste vom Server
  readonly books: Book[] = getDemoBooks();

  // todo:
  //   - Im Template mit @for über die Bücher iterieren
  //     und jeweils eine BookCard rendern
  //   - Dabei 'track book.id' angeben
}
